export const COUNTRY_NAMES = {
  'ad': 'Andorra',
  'ae': 'United Arab Emirates',
  'af': 'Afghanistan',
  'african-union': 'African Union',
  'ag': 'Antigua and Barbuda',
  'ai': 'Anguilla',
  'al': 'Albania',
  'am': 'Armenia',
  'ao': 'Angola',
  'aq': 'Antarctica',
  'ar': 'Argentina',
  'arab-league': 'Arab League',
  'as': 'American Samoa',
  'at': 'Austria',
  'au': 'Australia',
  'aw': 'Aruba',
  'ax': 'Åland Islands',
  'az': 'Azerbaijan',
  'ba': 'Bosnia and Herzegovina',
  'bb': 'Barbados',
  'bd': 'Bangladesh',
  'be': 'Belgium',
  'bf': 'Burkina Faso',
  'bg': 'Bulgaria',
  'bh': 'Bahrain',
  'bi': 'Burundi',
  'bj': 'Benin',
  'bl': 'Saint Barthélemy',
  'bm': 'Bermuda',
  'bn': 'Brunei',
  'bo': 'Bolivia',
  'bq-bo': 'Bonaire',
  'bq-sa': 'Saba',
  'bq-se': 'Sint Eustatius',
  'br': 'Brazil',
  'bs': 'Bahamas',
  'bt': 'Bhutan',
  'bv': 'Bouvet Island',
  'bw': 'Botswana',
  'by': 'Belarus',
  'bz': 'Belize',
  'ca': 'Canada',
  'cc': 'Cocos Islands',
  'cd': 'Democratic Republic of Congo',
  'cf': 'Central African Republic',
  'cg': 'Congo',
  'ch': 'Switzerland',
  'ci': 'Côte d\'Ivoire',
  'ck': 'Cook Island',
  'cl': 'Chile',
  'cm': 'Cameroon',
  'cn': 'China',
  'co': 'Colombia',
  'cr': 'Costa Rica',
  'cu': 'Cuba',
  'cv': 'Cape Verde',
  'cw': 'Curaçao',
  'cx': 'Christmas Island',
  'cy': 'Cyprus',
  'cz': 'Czech Republic',
  'de': 'Germany',
  'dj': 'Djibouti',
  'dk': 'Denmark',
  'dm': 'Dominica',
  'do': 'Dominican Republic',
  'dz': 'Algeria',
  'ec': 'Ecuador',
  'ee': 'Estonia',
  'eg': 'Egypt',
  'er': 'Eritrea',
  'es': 'Spain',
  'et': 'Ethiopia',
  'eu': 'European Union',
  'fi': 'Finland',
  'fj': 'Fiji',
  'fk': 'Falkland Islands',
  'fm': 'Micronesia (Federated States of)',
  'fo': 'Faroe Island',
  'fr': 'France',
  'ga': 'Gabon',
  'gb-nir': 'Northern Ireland',
  'gb-sct': 'Scotland',
  'gb-ukm': 'United Kingdom',
  'gb-wls': 'Wales',
  'gd': 'Grenada',
  'ge': 'Georgia',
  'gf': 'French Guiana',
  'gg': 'Guernsey',
  'gh': 'Ghana',
  'gi': 'Gibraltar',
  'gl': 'Greenland',
  'gm': 'Gambia',
  'gn': 'Guinea',
  'gp': 'Guadeloupe',
  'gq': 'Equatorial Guinea',
  'gr': 'Greece',
  'gs': 'South Georgia and the South Sandwich Islands',
  'gt': 'Guatemala',
  'gu': 'Guam',
  'gw': 'Guinea-Bissau',
  'gy': 'Guyana',
  'hk': 'Hong Kong',
  'hm': 'Heard Island and McDonald Islands',
  'hn': 'Honduras',
  'hr': 'Croatia',
  'ht': 'Haiti',
  'hu': 'Hungary',
  'id': 'Indonesia',
  'ie': 'Ireland',
  'im': 'Isle of Man',
  'in': 'India',
  'io': 'British Indian Ocean Territory',
  'iq': 'Iraq',
  'ir': 'Iran',
  'is': 'Iceland',
  'it': 'Italy',
  'je': 'Jersey',
  'jm': 'Jamaica',
  'jo': 'Jordan',
  'jp': 'Japan',
  'ke': 'Kenya',
  'kg': 'Kyrgyzstan',
  'kh': 'Cambodia',
  'ki': 'Kiribati',
  'km': 'Comoros',
  'kn': 'Saint Kitts and Nevis',
  'kp': 'Korea (the Democratic People\'s Republic of)',
  'kr': 'Korea (the Republic of)',
  'kw': 'Kuwait',
  'ky': 'Cayman Islands',
  'kz': 'Kazakhstan',
  'la': 'Lao People\'s Democratic Republic (the)',
  'lb': 'Lebanon',
  'lc': 'Saint Lucia',
  'li': 'Liechtenstein',
  'lk': 'Sri Lanka',
  'lr': 'Liberia',
  'ls': 'Lesotho',
  'lt': 'Lithuania',
  'lu': 'Luxembourg',
  'lv': 'Latvia',
  'ly': 'Libya',
  'ma': 'Morocco',
  'mc': 'Monaco',
  'md': 'Moldova (the Republic of)',
  'me': 'Montenegro',
  'mf': 'Saint Martin',
  'mg': 'Madagascar',
  'mh': 'Marshall Islands (the)',
  'mk': 'North Macedonia',
  'ml': 'Mali',
  'mm': 'Myanmar',
  'mn': 'Mongolia',
  'mo': 'Macao',
  'mp': 'Northern Mariana Islands (the)',
  'mq': 'Martinique',
  'mr': 'Mauritania',
  'ms': 'Montserrat',
  'mt': 'Malta',
  'mu': 'Mauritius',
  'mv': 'Maldives',
  'mw': 'Malawi',
  'mx': 'Mexico',
  'my': 'Malaysia',
  'mz': 'Mozambique',
  'na': 'Namibia',
  'nato': 'NATO',
  'nc': 'New Caledonia',
  'ne': 'Niger',
  'nf': 'Norfolk Island',
  'ng': 'Nigeria',
  'ni': 'Nicaragua',
  'nl': 'Netherlands',
  'no': 'Norway',
  'np': 'Nepal',
  'nr': 'Nauru',
  'nu': 'Niue',
  'nz': 'New Zealand',
  'om': 'Oman',
  'pa': 'Panama',
  'pe': 'Peru',
  'pf': 'French Polyesia',
  'pg': 'Papua New Guinea',
  'ph': 'Philippines (the)',
  'pk': 'Pakistan',
  'pl': 'Poland',
  'pm': 'Saint Pierre and Miquelon',
  'pn': 'Pitcairn',
  'pr': 'Puerto Rico',
  'ps': 'Palestine, State of',
  'pt': 'Portugal',
  'pw': 'Palau',
  'py': 'Paraguay',
  'qa': 'Qatar',
  're': 'Réunion',
  'ro': 'Romania',
  'rs': 'Serbia',
  'ru': 'Russian Federation (the)',
  'rw': 'Rwanda',
  'sa': 'Saudi Arabia',
  'sb': 'Solomon Islands',
  'sc': 'Seychelles',
  'sd': 'Sudan (the)',
  'se': 'Sweden',
  'sg': 'Singapore',
  'sh': 'Saint Helena, Ascension Island, Traistan da Cunha',
  'si': 'Slovenia',
  'sj': 'Svalbard, Jan Mayen',
  'sk': 'Slovakia',
  'sl': 'Sierra Leone',
  'sm': 'San Marino',
  'sn': 'Senegal',
  'so': 'Somalia',
  'sr': 'Suriname',
  'ss': 'South Sudan',
  'st': 'Sao Tome and Principe',
  'sv': 'El Salvador',
  'sx': 'Sint Maarten',
  'sy': 'Syrian Arab Republic (the)',
  'sz': 'Eswatini',
  'tc': 'Turks and Caicos Islands (the)',
  'td': 'Chad',
  'tf': 'French Southern Territories',
  'tg': 'Togo',
  'th': 'Thailand',
  'tj': 'Tajikistan',
  'tk': 'Tokelau',
  'tl': 'Timor-Leste',
  'tm': 'Turkmenistan',
  'tn': 'Tunisia',
  'to': 'Tonga',
  'tr': 'Turkey',
  'tt': 'Trinidad and Tobago',
  'tv': 'Tuvalu',
  'tw': 'Taiwan',
  'tz': 'Tanzania, the United Republic of',
  'ua': 'Ukraine',
  'ug': 'Uganda',
  'um': 'United States Minor Outlying Islands (the)',
  'un': 'United Nations',
  'us': 'United States of America',
  'us-ak': 'Alaska',
  'us-al': 'Alabama',
  'us-ar': 'Arkansas',
  'us-az': 'Arizona',
  'us-ca': 'California',
  'us-co': 'Colorado',
  'us-ct': 'Connecticut',
  'us-dc': 'District of Columbia',
  'us-de': 'Delaware',
  'us-fl': 'Florida',
  'us-ga': 'Georgia',
  'us-hi': 'Hawaii',
  'us-ia': 'Iowa',
  'us-id': 'Idaho',
  'us-il': 'Illinois',
  'us-in': 'Indiana',
  'us-ks': 'Kansas',
  'us-ky': 'Kentucky',
  'us-la': 'Louisiana',
  'us-ma': 'Massachusetts',
  'us-md': 'Maryland',
  'us-me': 'Maine',
  'us-mi': 'Michigan',
  'us-mn': 'Minnesota',
  'us-mo': 'Missouri',
  'us-mt': 'Montana',
  'us-nc': 'North Carolina',
  'us-nd': 'North Dakota',
  'us-ne': 'Nebraska',
  'us-nh': 'New Hampshire',
  'us-nj': 'New Jersey',
  'us-nm': 'New Mexico',
  'us-nv': 'Nevada',
  'us-ny': 'New York',
  'us-oh': 'Ohio',
  'us-ok': 'Oklahoma',
  'us-or': 'Oregon',
  'us-pa': 'Pennsylvania',
  'us-ri': 'Rhode Island',
  'us-sc': 'South Carolina',
  'us-sd': 'South Dakota',
  'us-tn': 'Tennessee',
  'us-tx': 'Texas',
  'us-ut': 'Utah',
  'us-va': 'Virginia',
  'us-vt': 'Vermont',
  'us-wa': 'Washington',
  'us-wi': 'Wisconsin',
  'us-wv': 'West Virginia',
  'us-wy': 'Wyoming',
  'uy': 'Uruguay',
  'uz': 'Uzbekistan',
  'va': 'Holy See',
  'vc': 'Saint Vincent and the Grenadines',
  've': 'Venezuela (Bolivarian Republic of)',
  'vg': 'Virgin Islands (British)',
  'vi': 'Virgin Islands (U.S.)',
  'vn': 'Vietnam',
  'vu': 'Vanuatu',
  'wf': 'Wallis and Futuna',
  'ws': 'Samoa',
  'ye': 'Yemen',
  'yt': 'Mayotte',
  'za': 'South Africa',
  'zm': 'Zambia',
  'zw': 'Zimbabwe',
  'gb': 'United Kingdom',
  'uk': 'United Kingdom',
  'arab': 'Arab League',
  'africa': 'African Union'
} as const;

export type FlagCode = keyof typeof COUNTRY_NAMES;

/** Normalize user input: trim, lowercase, uk->gb-ukm, gb->gb-ukm, el->gr. */
export function normalizeCode(input: string): string {
  const c = input.trim().toLowerCase();
  if (c === 'uk' || c === 'gb') return 'gb-ukm';
  if (c === 'el') return 'gr';
  return c;
}

export function countryName(code: string): string {
  const n = normalizeCode(code);
  const raw = inputKey(code);
  return (
    (COUNTRY_NAMES as Record<string, string>)[raw] ??
    (COUNTRY_NAMES as Record<string, string>)[n] ??
    n.toUpperCase()
  );
}

function inputKey(input: string): string {
  return input.trim().toLowerCase();
}
